### PR TITLE
Split utils

### PR DESCRIPTION
**Pull request by jiteshk23**
resolving #10 and some other minor stuff

### CODE REVIEW

**Comment by jiteshk23** [comment]
@singaurav The build is running fine on my machine. Can you please try at your end as well?

**Comment by jiteshk23** [comment]
[looks](https://stackoverflow.com/questions/25594644/warning-specialization-of-template-in-different-namespace) like its due to using g++ instead of clang on travis.

**Comment by jiteshk23** [comment]
@singaurav Build is fixed now.

**Review by singaurav — APPROVED** [review]
Nice

**Pull request merged**
